from enum import Enum


class ErrorCode(str, Enum):
    # user
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_INACTIVE = "USER_INACTIVE"

    # auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    NOT_AUTHORIZED = "NOT_AUTHORIZED"
    FORBIDDEN = "FORBIDDEN"

    # skill
    SKILL_NOT_FOUND = "SKILL_NOT_FOUND"
    SKILL_AlREADY_EXISTS = "SKILL_AlREADY_EXISTS"

    # skill activity
    SKILL_ACTIVITY_NOT_FOUND = "SKILL_ACTIVITY_NOT_FOUND"

    # morning
    MORNING_NOT_FOUND = "MORNING_NOT_FOUND"
    MORNING_ALREADY_EXISTS = "MORNING_ALREADY_EXISTS"

    # morning activity
    MORNING_ACTIVITY_NOT_FOUND = "MORNING_ACTIVITY_NOT_FOUND"

    # evening
    EVENING_NOT_FOUND = "EVENING_NOT_FOUND"
    EVENING_ALREADY_EXISTS = "EVENING_ALREADY_EXISTS"

    # setting
    SETTING_NOT_FOUND = "SETTING_NOT_FOUND"
    SETTING_ALREADY_EXISTS = "SETTING_ALREADY_EXISTS"

    # general
    UNPROCESSABLE_CONTENT = "UNPROCESSABLE_CONTENT"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
